# Generated by Django 3.2.5 on 2021-07-07 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tempo_estimado', models.FloatField(default=0)),
                ('tem_resp', models.BooleanField(default=False)),
                ('categoria', models.ManyToManyField(null=True, to='teamsandtasks.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nucleo', models.CharField(choices=[('EST', 'Estatística'), ('COMP', 'Computação')], max_length=4)),
                ('diretoria', models.CharField(choices=[('MKT', 'Marketing'), ('GP', 'Gestão de Pessoas'), ('VND', 'Vendas'), ('QLD', 'Qualidade'), ('PRS', 'Presidência'), ('JFN', 'Jurídico Financeiro')], max_length=4)),
                ('categorias', models.ManyToManyField(null=True, to='teamsandtasks.Categoria')),
                ('tarefas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamsandtasks.tarefa')),
            ],
        ),
    ]
