# Generated by Django 3.2.5 on 2021-07-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsandtasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='categorias',
            field=models.ManyToManyField(to='teamsandtasks.Categoria'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='categoria',
            field=models.ManyToManyField(to='teamsandtasks.Categoria'),
        ),
    ]
