# Generated by Django 3.2.5 on 2021-07-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsandtasks', '0002_auto_20210707_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='value',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tarefas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsandtasks.tarefa'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsandtasks.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='notas',
            field=models.ManyToManyField(to='teamsandtasks.Nota'),
        ),
    ]
