# Generated by Django 3.2.5 on 2021-07-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsandtasks', '0003_auto_20210707_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='notas',
        ),
        migrations.AddField(
            model_name='nota',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsandtasks.pessoa'),
        ),
    ]
