# Generated by Django 3.2.5 on 2021-07-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsandtasks', '0004_auto_20210707_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='categorias',
        ),
    ]
