# Generated by Django 3.2.5 on 2021-07-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsandtasks', '0005_remove_pessoa_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='tarefas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamsandtasks.tarefa'),
        ),
    ]
