# Generated by Django 3.2.5 on 2021-07-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsandtasks', '0006_alter_pessoa_tarefas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='tarefas',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tarefas',
            field=models.ManyToManyField(to='teamsandtasks.Tarefa'),
        ),
    ]
